name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug - Show directory before build
        run: |
          echo "Current directory contents before build:"
          ls -la
          echo "Current working directory:"
          pwd

      - name: Build
        run: npm run build

      - name: Debug - Show directory after build
        run: |
          echo "Current directory contents after build:"
          ls -la
          echo "Checking if dist directory exists:"
          if [ -d "dist" ]; then
            echo "dist directory exists"
            echo "Contents of dist directory:"
            ls -la dist/
          else
            echo "dist directory does not exist"
            echo "Creating dist directory with test file"
            mkdir -p dist
            echo "test" > dist/index.html
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages 